Insurance/UI.MVC/Models/CarViewModel.cs
using System.ComponentModel.DataAnnotations;
using Insurance.Domain;

namespace UI.MVC.Models
{
    public class CarViewModel
    {
        //required nrml niet nodig aangezien door string length
        [Required(ErrorMessage = "Brand is required")]
        [StringLength(20, ErrorMessage = "Error: Brand min. 2 CHAR & max. 20 CHAR ", MinimumLength = 2)]
        public string Brand { get; set; }
        
        
        [Required(ErrorMessage = "Fuel is required")]
        public Fuel Fuel { get; set; }

        
        //value type dus normaal niet required maar ik wil een error message
        [Required(ErrorMessage = "Seats amount is required")]
        [Range(1, 7, ErrorMessage = "Seats need to be between 1 and 7")]
        public short Seats { get; set; }

        
        [Required(ErrorMessage = "Milage is required")]
        [Range(0,10000000 , ErrorMessage = "Thats too much, not safe anymore")]
        public double Mileage { get; set; }

        
        public int Garage { get; set; }
        
        
        [Range(1,10000000 , ErrorMessage = "Verdomd dure auto amai")]
        public long? PurchasePrice { get; set; }
    }
}

Insurance/UI.MVC/Controllers/CarController.cs
using System.Linq;
using Insurance.BL;
using Insurance.DAL.EF;
using Insurance.Domain;
using Microsoft.AspNetCore.Mvc;
using UI.MVC.Models;

namespace UI.MVC.Controllers
{
    public class CarController : Controller
    {
        private readonly IManager _manager;

        public CarController(IManager manager)
        {
            _manager = manager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(_manager.GetAllCars());
        }

        [HttpGet]
        public IActionResult Add()
        {
            ViewData["garages"] = _manager.GetAllGarages().ToList();
            return View();
        }

        [HttpGet]
        public IActionResult Details(int numberplate)
        {
            //ViewBag.drivers = _manager.GetDriversOfCar(numberplate);
            return View(_manager.GetCarWithDrivers(numberplate));
        }

        [HttpPost]
        public IActionResult Add(CarViewModel cvm)
        {
            if (!ModelState.IsValid)
            {
                ViewData["garages"] = _manager.GetAllGarages().ToList();
                return View();
            }
            //Hij pakt de Mileage niet goed omdat er een foute omzetting gebeurd door regio: , & .
            var car = _manager.AddCar(cvm.PurchasePrice, cvm.Brand, cvm.Fuel, cvm.Seats, cvm.Mileage,
                _manager.GetGarage(cvm.Garage));
            return RedirectToAction("Details", "Car", new {numberplate = car.NumberPlate});
        }
    }
}

Insurance/UI.MVC/Controllers/DriverController.cs
using Insurance.BL;
using Insurance.DAL.EF;
using Microsoft.AspNetCore.Mvc;

namespace UI.MVC.Controllers
{
    public class DriverController : Controller
    {
        private readonly IManager _manager;
        public DriverController(IManager manager)
        {
            _manager = manager;
        }
        
        [HttpGet]
        public IActionResult Details(int socialnumber)
        {
            return View(_manager.GetDriver(socialnumber));
        }
    }
}

Insurance/UI.MVC/Views/Car/Add.cshtml
@using Insurance.Domain
@model CarViewModel
@{
    ViewBag.Title = "title";
    Layout = "_Layout";

    List<Garage> garages = (List<Garage>) ViewData["garages"];
}

<h2>Add a Car</h2>

<form asp-controller="Car" asp-action="Add" method="post">
    <div class="form-group">
        <label asp-for="Fuel">Fuel</label>
        <select asp-for="Fuel" asp-items="@Html.GetEnumSelectList<Fuel>()" class="form-control">
        </select>
        <span asp-validation-for="Fuel" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Brand">Brand</label>
        <input asp-for="Brand" class="form-control" type="text"/>
        <span asp-validation-for="Brand" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Mileage">Mileage (Double)</label>
        <!--  asp-is-invariant="true" is voor de komma en punt regio (werkt alsnog niet)-->
        <input asp-for="Mileage" type="number" step="0.01"  class="form-control"/>
        <span asp-validation-for="Mileage" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Seats">Amount of Seats</label>
        <input type="number" asp-for="Seats" min="1" max="8"/>
        <span asp-validation-for="Seats" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="PurchasePrice">Purchase Price</label>
        <input type="number" asp-for="PurchasePrice"/>
        <span asp-validation-for="PurchasePrice" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Garage">Garage</label>
        <select asp-for="Garage" class="form-control">
            <!-- https://stackoverflow.com/questions/58958881/how-to-make-form-input-for-list-of-objects -->
            <!-- Of mijn methode :)) -->
            @foreach (Garage g in garages)
            {
                <option value="@g.Id">@g.Name</option>
            }
        </select>
        <span asp-validation-for="Garage" class="text-danger"></span>
    </div>
    
    <div asp-validation-summary="All" class="text-danger"></div>
    <input type="submit" class="btn btn-primary"  value="Add"/>
    <input type="reset" class="btn btn-primary" value="Reset"/>
</form>

Insurance/UI.MVC/Views/Car/Details.cshtml
@using Insurance.Domain
@model Car

@{
    ViewBag.Title = "Car Details";
    Layout = "_Layout";
}

<h2>Car Details</h2>
<table>
    <tr>
        <th>Brand</th><td>@Model.Brand</td>
    </tr>
    <tr>
        <th>Fuel</th><td>@Model.Fuel</td>
    </tr>
    <tr>
        <th>Seats</th><td>@Model.Seats</td>
    </tr>
    <tr>
        <th>Mileage</th><td>@Model.Mileage</td>
    </tr>
    <tr>
        <th>Purchaseprice</th>
        @{
            var PurchasePrice = Model.PurchasePrice != null ? Model.PurchasePrice.ToString() : "Not Known";
        }
        <td>@PurchasePrice</td>
    </tr>
</table>

<h3>Drivers / Rentals for this car</h3>

<table class="table">
    <thead class="thead-light">
    <tr>
        <th scope="col">Name</th>
        <th scope="col">Date Of Birth</th>
        <th scope="col">Rent Price</th>
        <th scope="col">Total Days</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    @foreach (Rental r in Model.Rentals)
    {
        <tr>
            <td>@r.Driver.FirstName @r.Driver.LastName</td>
            <td>@r.Driver.DateOfBirth.ToString("dd/MM/yyyy")</td>
            <td>@Math.Round(r.Price,2)</td>
            @{
                var d = (r.EndDate.Date - r.StartDate.Date).TotalDays;
            }
            <td>@d</td>
            <td>
                <a asp-controller="Driver" asp-action="Details" asp-route-socialnumber="@r.Driver.SocialNumber">Details</a>
            </td>
        </tr>
    }
    </tbody>
</table>

Insurance/UI.MVC/Views/Car/Index.cshtml
@using Insurance.Domain
@model IEnumerable<Insurance.Domain.Car>

@{
    ViewBag.Title = "All Cars";
    Layout = "_Layout";
}

<!-- Titel -->
<h2>All Cars</h2>
<!-- tabel -->
<table class="table">
    <thead class="thead-light">
    <tr>
        <th scope="col">Brand</th>
        <th scope="col">Fuel</th>
        <th scope="col">Seats</th>
        <th scope="col">Miles</th>
        <th scope="col">Purchaseprice</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>

    @foreach (var car in Model)
    {
        <tr>
            <td>@car.Brand</td>
            <td>@car.Fuel</td>
            <td>@car.Seats</td>
            <td>@car.Mileage</td>
            @{
                var PurchasePrice = car.PurchasePrice != null ? car.PurchasePrice.ToString() : "Not Known";
            }
            <td>@PurchasePrice</td>
            <td>
                <a asp-controller="Car" asp-action="Details" asp-route-numberplate="@car.NumberPlate">Details</a>
            </td>
        </tr>
    }
    </tbody>
</table>